version: "3"
services:
  mariadb:
    build: src/mariadb
    container_name: mariadb
    restart: unless_stopped
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inslaption


  nginx:

  wordpress:

networks:
  inslaption:
    name: vinception
    driver: bridge

volumes: